/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaixasRouteImport } from './routes/caixas'
import { Route as EnderecamentoRouteImport } from './routes/enderecamento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixasRoute = CaixasRouteImport.update({
  id: '/caixas',
  path: '/caixas',
  getParentRoute: () => rootRouteImport,
} as any)
const EnderecamentoRoute = EnderecamentoRouteImport.update({
  id: '/enderecamento',
  path: '/enderecamento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caixas': typeof CaixasRoute
  '/enderecamento': typeof EnderecamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caixas': typeof CaixasRoute
  '/enderecamento': typeof EnderecamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caixas': typeof CaixasRoute
  '/enderecamento': typeof EnderecamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/caixas' | '/enderecamento'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/caixas' | '/enderecamento'
  id: '__root__' | '/' | '/caixas' | '/enderecamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaixasRoute: typeof CaixasRoute
  EnderecamentoRoute: typeof EnderecamentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixas': {
      id: '/caixas'
      path: '/caixas'
      fullPath: '/caixas'
      preLoaderRoute: typeof CaixasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enderecamento': {
      id: '/enderecamento'
      path: '/enderecamento'
      fullPath: '/enderecamento'
      preLoaderRoute: typeof EnderecamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaixasRoute: CaixasRoute,
  EnderecamentoRoute: EnderecamentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
