/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaixasRouteImport } from './routes/caixas'
import { Route as EnderecamentoRouteImport } from './routes/enderecamento'
import { Route as InventariosRouteImport } from './routes/inventarios'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MovimentacoesRouteImport } from './routes/movimentacoes'
import { Route as RecebimentosRouteImport } from './routes/recebimentos'
import { Route as ScannerRouteImport } from './routes/scanner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixasRoute = CaixasRouteImport.update({
  id: '/caixas',
  path: '/caixas',
  getParentRoute: () => rootRouteImport,
} as any)
const EnderecamentoRoute = EnderecamentoRouteImport.update({
  id: '/enderecamento',
  path: '/enderecamento',
  getParentRoute: () => rootRouteImport,
} as any)
const InventariosRoute = InventariosRouteImport.update({
  id: '/inventarios',
  path: '/inventarios',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesRoute = MovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentosRoute = RecebimentosRouteImport.update({
  id: '/recebimentos',
  path: '/recebimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caixas': typeof CaixasRoute
  '/enderecamento': typeof EnderecamentoRoute
  '/inventarios': typeof InventariosRoute
  '/mapa': typeof MapaRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/recebimentos': typeof RecebimentosRoute
  '/scanner': typeof ScannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caixas': typeof CaixasRoute
  '/enderecamento': typeof EnderecamentoRoute
  '/inventarios': typeof InventariosRoute
  '/mapa': typeof MapaRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/recebimentos': typeof RecebimentosRoute
  '/scanner': typeof ScannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caixas': typeof CaixasRoute
  '/enderecamento': typeof EnderecamentoRoute
  '/inventarios': typeof InventariosRoute
  '/mapa': typeof MapaRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/recebimentos': typeof RecebimentosRoute
  '/scanner': typeof ScannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caixas'
    | '/enderecamento'
    | '/inventarios'
    | '/mapa'
    | '/movimentacoes'
    | '/recebimentos'
    | '/scanner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caixas'
    | '/enderecamento'
    | '/inventarios'
    | '/mapa'
    | '/movimentacoes'
    | '/recebimentos'
    | '/scanner'
  id:
    | '__root__'
    | '/'
    | '/caixas'
    | '/enderecamento'
    | '/inventarios'
    | '/mapa'
    | '/movimentacoes'
    | '/recebimentos'
    | '/scanner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaixasRoute: typeof CaixasRoute
  EnderecamentoRoute: typeof EnderecamentoRoute
  InventariosRoute: typeof InventariosRoute
  MapaRoute: typeof MapaRoute
  MovimentacoesRoute: typeof MovimentacoesRoute
  RecebimentosRoute: typeof RecebimentosRoute
  ScannerRoute: typeof ScannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixas': {
      id: '/caixas'
      path: '/caixas'
      fullPath: '/caixas'
      preLoaderRoute: typeof CaixasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enderecamento': {
      id: '/enderecamento'
      path: '/enderecamento'
      fullPath: '/enderecamento'
      preLoaderRoute: typeof EnderecamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventarios': {
      id: '/inventarios'
      path: '/inventarios'
      fullPath: '/inventarios'
      preLoaderRoute: typeof InventariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes': {
      id: '/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof MovimentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimentos': {
      id: '/recebimentos'
      path: '/recebimentos'
      fullPath: '/recebimentos'
      preLoaderRoute: typeof RecebimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaixasRoute: CaixasRoute,
  EnderecamentoRoute: EnderecamentoRoute,
  InventariosRoute: InventariosRoute,
  MapaRoute: MapaRoute,
  MovimentacoesRoute: MovimentacoesRoute,
  RecebimentosRoute: RecebimentosRoute,
  ScannerRoute: ScannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
